AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rspec
  - rubocop-rake